# Generated by Django 3.2.7 on 2021-09-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.FileField(upload_to='images/')),
                ('ModelName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.laptops')),
            ],
        ),
    ]
